package com.addressbook.springboot.api.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/*
 * Specifying JPA hibernate annotation for defining its entites and attributes
 * Providing custom name for the table to be created
 */
@Entity
@Table(name = "addressbook")
public class AddressBook {

	/*
	 * primary Key as ID and setting value to autogenerated
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;
	private String fname;
	private String lname;
	private String phone;
	private String address;
	
/*
 * The lombok  annotations are not working 
 * so specifying some boiler plate construtor
 * and getter setter them explictly 
 */

//	Constructor without paramaters
	public AddressBook() {
		super();
	}

//	Constructor with all attributes as parameters
	public AddressBook(Long id, String fname, String lname, String phone, String address) {
		super();
		this.id = id;
		this.fname = fname;
		this.lname = lname;
		this.phone = phone;
		this.address = address;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getFname() {
		return fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
